server:
  port: 8088

spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 45672
                username: guest
                password: guest
                virtual-host: /
      bindings:
        saveOrderOutput:
          destination: exchange-saveOrder
          content-type: application/json
          default-binder: defaultRabbit
          group: saveOrderGroup